#ifndef CONSTANTS_H
#define CONSTANTS_H

#define MAX_FILENAME_LENGTH 256
#define CLASS               "class"
#define CONSTRUCTOR         "constructor"
#define FUNCTION            "function"
#define METHOD              "method"
#define FIELD               "field"
#define STATIC              "static"
#define VAR                 "var"
#define INT                 "int"
#define CHAR                "char"
#define BOOLEAN             "boolean"
#define VOID                "void"
#define J_TRUE              "true"
#define J_FALSE             "false"
#define J_NULL              "null"
#define THIS                "this"
#define LET                 "let"
#define DO                  "do"
#define IF                  "if"
#define ELSE                "else"
#define WHILE               "while"
#define RETURN              "return"
#define LEFT_BRACE          "{"
#define RIGHT_BRACE         "}"
#define LEFT_PAREN          "("
#define RIGHT_PAREN         ")"
#define LEFT_BRACKET        "["
#define RIGHT_BRACKET       "]"
#define PERIOD              "."
#define COMMA               ","
#define SEMICOLON           ";"
#define PLUS                "+"
#define MINUS               "-"
#define ASTERISK            "*"
#define SLASH               "/"
#define AMPERSAND           "&"
#define PIPE                "|"
#define LESS_THAN           "<"
#define GREATER_THAN        ">"
#define EQUAL               "="
#define TILDE               "~"
#define UNDERSCORE          "_"

#endif
